### ISSUE TITLE
Issue with responsive sizing

### ISSUE THREAD

**Issue by ZwickerZ** [ZwickerZ/leafy-decorations#1]
@charlie-quinn Markbot has okay'd me for the lower window sizes, 320px and 400px. However, when sizing up to 608px+ the background image in the banner is too a little too tall. When bringing the top padding lower to accommodate the larger screen sizes, of course, the background image is now too short for the smaller sizes. Is there something I am missing?

**Comment by ZwickerZ** [comment]
@charlie-quinn here top of ya list

**Comment by charlie-quinn** [comment]
You're so close!

Your `leaf-bg.svg` was probably exported incorrectly, but Markbot doesn't seem to have an issue with it, so that's fine.

### CSS
- [x] on `.banner` change the background position to `center bottom`
  - [x] also add `border-bottom: 3px solid #2d5a4d;` to match the lovely border we have sitting below our `.masthead`
- [x] on `.banner-content` change the background image's position to `.75em 180px`
  - [x] also change the width to `100px`
  - _we're using pixel values here because we don't want the position to change no matter what the browser width_
- [x] on `.banner-content` change the padding-top to `padding-top: 300px;`
  - _we're using a pixel value here because we want the padding to stay the same no matter what the width of the browser is_

**Comment by ZwickerZ** [comment]
Did all those, had most of them already. Now the screenshots are worse? @charlie-quinn

**Comment by charlie-quinn** [comment]
I'll take a look at this again later tonight. 👀

**Comment by charlie-quinn** [comment]
- [ ] remove `padding-top: 11.75em;` from `.banner`

**Comment by charlie-quinn** [comment]
⚠️`Reminder: please close this issue once it has been resolved.`

**Comment by ZwickerZ** [comment]
thank you!
